// Code generated by go-bindata.
// sources:
// schema/query.graphql
// schema/schema.graphql
// schema/type/article.graphql
// schema/type/hello.graphql
// schema/type/post.graphql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _schemaQueryGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4c\xcb\x31\x0a\x02\x31\x10\x85\xe1\x7e\x4f\xf1\x16\x1b\x6d\x3c\x40\x3a\xc1\xc6\x4e\xd1\x0b\x2c\xfa\x34\x81\x21\x13\x66\xc6\x22\x88\x77\x17\xb2\x8d\xed\xff\xbd\xb7\xc1\x2d\x13\x97\x37\xad\x23\x7a\x23\x8c\xcd\xe8\xac\xe1\x58\x44\xa0\x4f\x44\x26\x58\xc3\x3a\x9a\x96\x1a\xbe\x9f\xc6\x70\xfd\x7c\x26\x00\xc8\x14\xd1\x84\x6b\x58\xa9\xaf\x79\xa4\xc5\xa2\xdc\x85\xdb\xf2\x48\x38\x1d\xe7\x5d\xc2\x61\x2d\x43\x9b\x7a\xfc\xd1\x59\x3d\xa6\xef\x2f\x00\x00\xff\xff\x73\xc1\x64\x42\x8c\x00\x00\x00")

func schemaQueryGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaQueryGraphql,
		"schema/query.graphql",
	)
}

func schemaQueryGraphql() (*asset, error) {
	bytes, err := schemaQueryGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/query.graphql", size: 140, mode: os.FileMode(436), modTime: time.Unix(1519329122, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaSchemaGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2a\x4e\xce\x48\xcd\x4d\x54\xa8\xe6\x52\x50\x50\x50\x28\x2c\x4d\x2d\xaa\xb4\x52\x08\x04\x51\x5c\xb5\x80\x00\x00\x00\xff\xff\x54\xe0\x78\x3a\x1b\x00\x00\x00")

func schemaSchemaGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaSchemaGraphql,
		"schema/schema.graphql",
	)
}

func schemaSchemaGraphql() (*asset, error) {
	bytes, err := schemaSchemaGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/schema.graphql", size: 27, mode: os.FileMode(436), modTime: time.Unix(1519165664, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaTypeArticleGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2a\xa9\x2c\x48\x55\x70\x2c\x2a\xc9\x4c\xce\x49\x55\xa8\xe6\xe2\xe4\x54\x56\x08\xc9\x48\x55\xf0\x74\x51\xc8\x4f\x53\x28\xc9\x48\x55\x48\x84\xc8\x71\x71\x72\x66\xa6\x58\x29\x78\xba\x28\x72\x29\x40\x01\x44\x65\x71\x4e\x69\x3a\xba\x5a\x98\x0a\x90\x9c\x95\x42\x70\x49\x51\x66\x5e\xba\x22\xdc\xec\x92\xcc\x92\x9c\x54\x4c\xe3\xc1\xc2\x08\xd5\xb5\x80\x00\x00\x00\xff\xff\x5c\x61\xe7\x3d\x9a\x00\x00\x00")

func schemaTypeArticleGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaTypeArticleGraphql,
		"schema/type/article.graphql",
	)
}

func schemaTypeArticleGraphql() (*asset, error) {
	bytes, err := schemaTypeArticleGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/type/article.graphql", size: 154, mode: os.FileMode(436), modTime: time.Unix(1519242508, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaTypeHelloGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2a\xa9\x2c\x48\x55\xf0\x48\xcd\xc9\xc9\x57\xa8\xe6\x52\x50\x50\x50\xc8\x4c\xb1\x52\xf0\x74\x51\x04\xb3\x93\xf3\xf3\x4a\x52\xf3\x4a\xac\x14\x82\x4b\x8a\x32\xf3\xd2\x15\xb9\x6a\x01\x01\x00\x00\xff\xff\xfe\x2a\x04\x6c\x2f\x00\x00\x00")

func schemaTypeHelloGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaTypeHelloGraphql,
		"schema/type/hello.graphql",
	)
}

func schemaTypeHelloGraphql() (*asset, error) {
	bytes, err := schemaTypeHelloGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/type/hello.graphql", size: 47, mode: os.FileMode(436), modTime: time.Unix(1519241009, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaTypePostGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2a\xa9\x2c\x48\x55\x08\xc8\x2f\x2e\x51\xa8\xe6\xe2\xe4\x54\x56\x08\xc9\x48\x55\xf0\x74\x51\xc8\x4f\x53\x28\xc9\x48\x55\x28\xc8\x2f\x2e\xe1\xe2\xe4\xcc\x4c\xb1\x52\xf0\x74\x51\xe4\x52\x80\x02\x88\xb2\xe2\x9c\xd2\x74\x34\x85\x20\x21\x2b\x85\xe0\x92\xa2\xcc\xbc\x74\x45\xb8\x79\x25\x99\x25\x39\xa9\x28\x2a\x61\x06\x81\x65\x10\x1a\x6a\x01\x01\x00\x00\xff\xff\x9d\x1c\x48\x7c\x8e\x00\x00\x00")

func schemaTypePostGraphqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaTypePostGraphql,
		"schema/type/post.graphql",
	)
}

func schemaTypePostGraphql() (*asset, error) {
	bytes, err := schemaTypePostGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/type/post.graphql", size: 142, mode: os.FileMode(436), modTime: time.Unix(1519329110, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"schema/query.graphql": schemaQueryGraphql,
	"schema/schema.graphql": schemaSchemaGraphql,
	"schema/type/article.graphql": schemaTypeArticleGraphql,
	"schema/type/hello.graphql": schemaTypeHelloGraphql,
	"schema/type/post.graphql": schemaTypePostGraphql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"schema": &bintree{nil, map[string]*bintree{
		"query.graphql": &bintree{schemaQueryGraphql, map[string]*bintree{}},
		"schema.graphql": &bintree{schemaSchemaGraphql, map[string]*bintree{}},
		"type": &bintree{nil, map[string]*bintree{
			"article.graphql": &bintree{schemaTypeArticleGraphql, map[string]*bintree{}},
			"hello.graphql": &bintree{schemaTypeHelloGraphql, map[string]*bintree{}},
			"post.graphql": &bintree{schemaTypePostGraphql, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

